image: gradle:6.8-jdk11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - jar
  - publish

build:
  stage: build
  script:
    - 'gradle build'
  cache:
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - build
jar:
  needs:
    - job: build
  stage: jar
  script:
    - 'gradle jar'
  except:
    - master
    - dev
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 days
  cache:
  - key: "$CI_COMMIT_REF_SLUG"
    paths:
      - build
publish:
  needs:
    - job: build
  stage: publish
  script:
    - 'gradle publish'
  only:
    - master
    - dev
  artifacts:
    paths:
      - build/libs/*.jar
  cache:
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - build